# Generated by Django 3.2.16 on 2022-12-12 11:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='addresses', to='employee.employee'),
        ),
    ]
